# Header
menu:
  首页: /
  关于我: https://cdn.qiujun.me/resume.pdf

# SubNav
subnav:
  mail: mailto:i@qiujun.me
  github: https://github.com/qious
  rss: /atom.xml
  # weibo: #
  # zhihu: #
  #qq: #
  #weixin: #
  #jianshu: #
  #douban: #
  #segmentfault: #
  #bilibili: #
  #acfun: #
  #facebook: #
  #google: #
  #twitter: #
  #linkedin: #

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay:
# 微信二维码图片地址
weixin:

# Miscellaneous
baidu_analytics: 20fb39a5201df3690d5ce8cc36e7d1f7
google_analytics:
favicon:

#你的头像url
avatar: //cdn.qiujun.me/images/logo.png!avatar

#是否开启分享
share_jia: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo:

upyun_league: true

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#475669'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: 所有文章
  friends: 友情链接
  aboutme: false

friends:
  "陈康'Blog": http://www.kchen.cn/
  刘卓旻的博客: http://trumi.cn/
  TT的博客: http://blog.silenttt.top/
  孙宗正的博客: https://zzsun.cc/
  wangkechun的博客: http://blog.hi-hi.cn/
  JailBreak的博客: http://vgee.cn/
  猫尾博客: https://cattail.me/
  Blog via Mateor: https://mateor.me
  "ltaoo's web": https://ltaoo.github.io/

aboutme: false
