# Header
menu:
  首页: /
  所有文章: /archives/
  个人简介: /about.html
  旧版博客: https://old.qiujun.me

# SubNav
subnav:
  mail: mailto:qious@qq.com
  github: https://github.com/qious
  rss: /atom.xml
  #weibo: "#"
  #zhihu: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
analytics:
  baidu: 20fb39a5201df3690d5ce8cc36e7d1f7
# favicon: /logo.png

#你的头像url
avatar: /logo.png
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
duoshuo: qiujun
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  陈康'Blog: http://www.kchen.cn/
  wangkechun的博客: http://blog.hi-hi.cn/
  JailBreak的博客: http://vgee.cn/
  Trumi的博客: http://trumi.cn/
  TT的博客: http://blog.silenttt.top/
  猫尾博客: https://cattail.me/

#是否开启“关于我”。
#不开启——
aboutme: false
#开启——
# aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
